language: go

go:
  - "1.17.x"

go_import_path: github.com/devopsext/chatops

before_install:
  - env GO111MODULE=on

install:
  - go get -t -v ./ ./cmd ./bot ./processor

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./ ./cmd ./bot ./processor
  - go build ./ ./cmd ./bot ./processor

after_success:
  - bash <(curl -s https://codecov.io/bash)